policy_path: ../../checkpoints/policy.onnx
reference_fps: 50.0
transition_steps: 100
switch_tail_keep_steps: 8
ref_max_len: 8192
motion_source:
  type: npz
  udp:
    enable: true
    host: 127.0.0.1
    port: 28562
  vr:
    req_addr: tcp://127.0.0.1:28701
    rep_addr: tcp://127.0.0.1:28702
    ctrl_addr: tcp://127.0.0.1:28703
    low_watermark: 13
    high_watermark: 16
    inflight_lifetime_steps: 0
  npz:
    primary: walk_turn
    loop: true
    start_at_primary: true
motions:
- name: walk_turn
  path: motions/walk_turn.npz
  start: 0
  end: -1
- name: jump_heavy
  path: motions/jump_heavy.npz
  start: 0
  end: -1
motion_clips:
- name: default
  joint_pos:
  - -0.312
  - 0.0
  - 0.0
  - 0.669
  - -0.363
  - 0.0
  - -0.312
  - 0.0
  - 0.0
  - 0.669
  - -0.363
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.2
  - 0.2
  - 0.0
  - 0.6
  - 0.0
  - 0.0
  - 0.0
  - 0.2
  - -0.2
  - 0.0
  - 0.6
  - 0.0
  - 0.0
  - 0.0
  root_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  root_pos:
  - 0.0
  - 0.0
  - 0.78
action_joint_names:
- left_hip_pitch_joint
- left_hip_roll_joint
- left_hip_yaw_joint
- left_knee_joint
- left_ankle_pitch_joint
- left_ankle_roll_joint
- right_hip_pitch_joint
- right_hip_roll_joint
- right_hip_yaw_joint
- right_knee_joint
- right_ankle_pitch_joint
- right_ankle_roll_joint
- waist_yaw_joint
- waist_roll_joint
- waist_pitch_joint
- left_shoulder_pitch_joint
- left_shoulder_roll_joint
- left_shoulder_yaw_joint
- left_elbow_joint
- left_wrist_roll_joint
- left_wrist_pitch_joint
- left_wrist_yaw_joint
- right_shoulder_pitch_joint
- right_shoulder_roll_joint
- right_shoulder_yaw_joint
- right_elbow_joint
- right_wrist_roll_joint
- right_wrist_pitch_joint
- right_wrist_yaw_joint
action_scale:
- 0.5475464629911068
- 0.35066146637882434
- 0.5475464629911068
- 0.35066146637882434
- 0.43857731392336724
- 0.43857731392336724
- 0.5475464629911068
- 0.35066146637882434
- 0.5475464629911068
- 0.35066146637882434
- 0.43857731392336724
- 0.43857731392336724
- 0.5475464629911068
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.07450087032950714
- 0.07450087032950714
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.43857731392336724
- 0.07450087032950714
- 0.07450087032950714
encoder_offset:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
reference_joint_names:
- left_hip_pitch_joint
- left_hip_roll_joint
- left_hip_yaw_joint
- left_knee_joint
- left_ankle_pitch_joint
- left_ankle_roll_joint
- right_hip_pitch_joint
- right_hip_roll_joint
- right_hip_yaw_joint
- right_knee_joint
- right_ankle_pitch_joint
- right_ankle_roll_joint
- waist_yaw_joint
- waist_roll_joint
- waist_pitch_joint
- left_shoulder_pitch_joint
- left_shoulder_roll_joint
- left_shoulder_yaw_joint
- left_elbow_joint
- left_wrist_roll_joint
- left_wrist_pitch_joint
- left_wrist_yaw_joint
- right_shoulder_pitch_joint
- right_shoulder_roll_joint
- right_shoulder_yaw_joint
- right_elbow_joint
- right_wrist_roll_joint
- right_wrist_pitch_joint
- right_wrist_yaw_joint
